server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flavourfly?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ersunil1711@gmail.com
    password: dlysnfjcuqupvdps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


app:
  jwt:
    secret: "replace-with-a-256-bit-secret-change-me-change-me-change-me"
    expiration: 86400000

cors:
  allowed-origins: "http://localhost:3000,http://localhost:5173"
  allowed-methods: "GET,POST,PATCH,PUT,DELETE,OPTIONS"
  allowed-headers: "Authorization,Content-Type"
